import Navigation from "@/components/layout/navigation";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "./globals.css";


const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Navigation />
        <div className={"p-8"}>{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
